In [2]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,9,11,13,17,19,23,29,31])

In [3]:
array1

array([ 2,  3,  5,  7,  9, 11, 13, 17, 19, 23, 29, 31])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(12,)

In [7]:
array2 =  np.array([[2,  3,  5,  7],  [9, 11, 13, 17], [19, 23, 29, 31]])

In [8]:
array2.shape

(3, 4)

In [9]:
array2

array([[ 2,  3,  5,  7],
       [ 9, 11, 13, 17],
       [19, 23, 29, 31]])

In [10]:
array1.size

12

In [11]:
array2.size

12

In [12]:
import matplotlib.pyplot as plt

In [13]:
array1[1]

3

In [14]:
array1[-1]

31

In [15]:
array1[[1, 3, 4]]

array([3, 7, 9])

In [16]:
array3 = np.array([2, 1, 3])

In [17]:
array3

array([2, 1, 3])

In [20]:
array4 = array1[array3]

In [21]:
array4

array([5, 3, 7])

In [22]:
array1[1:]

array([ 3,  5,  7,  9, 11, 13, 17, 19, 23, 29, 31])

In [23]:
array1[:3]

array([2, 3, 5])

In [25]:
array1[2:11:2]

array([ 5,  9, 13, 19, 29])

In [3]:
arr1 = np.arange(10)

In [4]:
arr2 = np.arange(10, 20)

In [5]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
arr1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
arr1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arr1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [12]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [13]:
arr1 * arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [14]:
arr1 / arr2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [15]:
arr1 > 6

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [16]:
arr1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [17]:
booleans = np.array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [18]:
np.where(booleans)

(array([0, 2, 4, 6, 8], dtype=int64),)